baseurl = "https://looking-vita-epfl.github.io/"
title = "LOOK dataset"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/background.jpg"
  SEOTitle = "-"
  keyword = "Autonomous  Vehicles,  Computer Vision,  Deep Learning,  Eye Contact Detection"
  slogan = "Do pedestrians pay attention? Eye contact detection in the wild - official website"

  image_404 = "img/not-found.jpeg"
  title_404 = "Page not found!"
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Baidu Analytics
  #ba_track_id = ""

  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  #disqus_proxy = ""
  #disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  reward = false

  # Activate features in sidebar
  featured_tags = false
  featured_condition_size = 1

  friends = false
  bookmarks = false
  about_me = false

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  email          = "lookingdataset@gmail.com"
  github         = "https://github.com/vita-epfl"


  [[params.addtional_menus]]
  title =  "DATASET"
  href =  "/top/dataset/"
  [[params.addtional_menus]]
  title =  "AUTHORS"
  href =  "/top/authors/"
  [[params.addtional_menus]]
  title =  "CODE"
  href =  "/top/github/"
  [[params.addtional_menus]]
  title =  "CONTRIBUTE"
  href =  "/top/contribute/"
  [[params.addtional_menus]]
  title =  "LICENSES"
  href =  "/top/licenses/"


[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
